// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAezppEj_m91ogvW7dZM8vHTHy-YsLL7Us',
    appId: '1:872081760818:web:fc64bd083c71f692c0122b',
    messagingSenderId: '872081760818',
    projectId: 'rotina-kids-plus',
    authDomain: 'rotina-kids-plus.firebaseapp.com',
    storageBucket: 'rotina-kids-plus.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAyfR2ppCr-fbPt5DB4fPVAbT6AphQQfQ',
    appId: '1:872081760818:android:1d76ef4049b1ba8ac0122b',
    messagingSenderId: '872081760818',
    projectId: 'rotina-kids-plus',
    storageBucket: 'rotina-kids-plus.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZ4ia53SHsuABnO2xi-ifm5_i9P3xxZT4',
    appId: '1:872081760818:ios:8b1d93d1db631433c0122b',
    messagingSenderId: '872081760818',
    projectId: 'rotina-kids-plus',
    storageBucket: 'rotina-kids-plus.firebasestorage.app',
    iosBundleId: 'br.com.felipe.rotinakidsplus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAezppEj_m91ogvW7dZM8vHTHy-YsLL7Us',
    appId: '1:872081760818:web:81bc192fe67ee4cdc0122b',
    messagingSenderId: '872081760818',
    projectId: 'rotina-kids-plus',
    authDomain: 'rotina-kids-plus.firebaseapp.com',
    storageBucket: 'rotina-kids-plus.firebasestorage.app',
  );
}
